<nav class="navbar navbar-expand-lg menu">
	<div class="col-3">
		<div class="container">
			<div class="navbar-nav">
				<img src="/img/twitter_logo.png" class="menuIco" />			  	
			</div>
		</div>
	</div>
	<div class="col-5">
		<div class="container">
			<a href="/timeline" class="textHome">Página Inicial</a>
		</div>
	</div>
	<div class="col-4">
		<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>	
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"> <?= htmlspecialchars(ucfirst($this->view->info_usuario['nome'])) ?> </span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"> <?= $this->view->total_tweets['total_tweets'] ?> </span> <!-- Utilizando o indice definido dentro das querys -->
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"> <?= $this->view->total_seguindo['total_seguindo'] ?> </span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"> <?= $this->view->total_seguidores['total_seguidores'] ?> </span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form method="get" action="/seguirPessoas">
								<div class="input-group mb-3">
									<input type="text" name="pesquisarPor" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<!-- Pesquisando Usuarios pelo nome -->
			<?php foreach($this->view->usuarios as $indice_array => $usuario) { ?>
				<div class="row mb-2">
					<div class="col">
						<div class="card">
							<div class="card-body">
								<div class="row">
									<div class="col-md-6">
										<a href="#" style="font-size: 15px; color: #24b4ed; font-weight: 600; text-decoration: none;">
											<?= htmlspecialchars(ucfirst($usuario['nome'])) ?>
										</a>
									</div>							
									<div class="col-md-6 d-flex justify-content-end">
										<div>
											<!-- Visibilidade dos Buttons caso esteja seguindo ou não -->
											<?php if ($usuario['seguindo_sn'] == 0) { ?>											
												<a href="/acao?acao=seguirUsuario&id_usuario=<?=$usuario['id']?>" class="btn btn-success">Seguir</a>
											<?php } ?>

											<?php if ($usuario['seguindo_sn'] == 1) { ?>											
												<a href="/acao?acao=deixarSeguir&id_usuario=<?=$usuario['id']?>" class="btn btn-danger"><i class="fas fa-user-slash"></i></a>
											<?php } ?>

										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			<?php } ?>

		</div>
	</div>
</div>