<nav class="navbar navbar-expand-lg menu">
	<div class="col-3">
		<div class="container">
			<div class="navbar-nav">
				<img src="/img/twitter_logo.png" class="menuIco" />			  	
			</div>
		</div>
	</div>
	<div class="col-5">
		<div class="container">
			<a href="/timeline" class="textHome">Página Inicial</a>
		</div>
	</div>
	<div class="col-4">
		<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>	
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
					
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"> <?= htmlspecialchars(ucfirst($this->view->info_usuario['nome'])) ?> </span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"> <?= $this->view->total_tweets['total_tweets'] ?> </span> <!-- Utilizando o indice definido dentro das querys -->
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"> <?= $this->view->total_seguindo['total_seguindo'] ?> </span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"> <?= $this->view->total_seguidores['total_seguidores'] ?> </span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method='post' action="/tweet">
						<textarea class="form-control" name="tweet" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<!-- Criar foreach para listar os tweets -->
			<?php foreach($this->view->tweets as $id_tweet => $tweet_dados) { ?>
				<div class="row tweet">
					<div class="col">
						<p>	
							<a href="#" style="font-size: 15px; color: #24b4ed; font-weight: 600; text-decoration: none;">
								<?= htmlspecialchars(ucfirst($tweet_dados['nome'])) ?>
							</a>
							<small>
								<span class="text-muted"> @<?= htmlspecialchars(ucfirst($tweet_dados['nome'])) ?> </span>
								<span class="text text-muted"> <?= $tweet_dados['data'] ?> </span>
							</small>
						</p>
						<p style="font-size: 14px; color: #4550b5; font-weight: 450; font-style: italic;"> 
							<?= htmlspecialchars($tweet_dados['tweet']) ?> 
						</p>

						<br />

						<!-- Condição para que o botão remover aparece somente para o usuario Autenticado em sua timeline -->
						<?php if($tweet_dados['id_usuario'] == $_SESSION['id']) { ?>
							<form>
								<div class="col d-flex justify-content-end">
									<button type="submit" class="btn btn-danger"><small>Remover</small></button>
								</div>
							</form>
						<?php } ?>
					</div>
				</div>
			<?php } ?>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/seguirPessoas" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>